# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Category

# Model Form Field configuration
form: $/lbaig/catalog/models/category/fields.yaml

# Model Class name
modelClass: Lbaig\Catalog\Models\Category

# Default redirect location
defaultRedirect: lbaig/catalog/categories

# Create page
create:
    title: Create Category
    redirect: lbaig/catalog/categories/update/:id
    redirectClose: lbaig/catalog/categories

# Update page
update:
    title: Edit Category
    redirect: lbaig/catalog/categories
    redirectClose: lbaig/catalog/categories

# Preview page
preview:
    title: Preview Category
