# ===================================
#  Relation Behavior Config
# ===================================

options:
    label: Property Options
    view:
        list: $/lbaig/catalog/models/propertyoption/columns.yaml
        toolbarButtons: create|delete
        defaultSort:
            column: sort_order
            direction: asc
    manage:
        form: $/lbaig/catalog/models/propertyoption/fields.yaml
        recordsPerPage: 10
