# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: Reorder Products

# Attribute name
nameFrom: name

# Model Class name
modelClass: Lbaig\Catalog\Models\Product

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder_toolbar
