# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    category:
        label: Category
        modelClass: Lbaig\Catalog\Models\Category
        conditions: category_id in (:filtered)
        nameFrom: name

    active:
        label: Active
        type: checkbox
        conditions: active=true
