# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Product

# Model Form Field configuration
form: $/lbaig/catalog/models/product/fields.yaml

# Model Class name
modelClass: Lbaig\Catalog\Models\Product

# Default redirect location
defaultRedirect: lbaig/catalog/products

# Create page
create:
    title: Create Product
    redirect: lbaig/catalog/products/update/:id
    redirectClose: lbaig/catalog/products

# Update page
update:
    title: Edit Product
    redirect: lbaig/catalog/products
    redirectClose: lbaig/catalog/products

# Preview page
preview:
    title: Preview Product
