# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Option

# Model Form Field configuration
form: $/lbaig/catalog/models/option/fields.yaml

# Model Class name
modelClass: Lbaig\Catalog\Models\Option

# Default redirect location
defaultRedirect: lbaig/catalog/options

# Create page
create:
    title: Create Option
    redirect: lbaig/catalog/options/update/:id
    redirectClose: lbaig/catalog/options

# Update page
update:
    title: Edit Option
    redirect: lbaig/catalog/options
    redirectClose: lbaig/catalog/options

# Preview page
preview:
    title: Preview Option
